### PR TITLE
Update version to 2.14

### PR DESCRIPTION
**Pull request by rhpvorderman**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

I am currently [trying to build isa-l on mac os](https://github.com/conda-forge/isa-l-feedstock/pull/5). It should work however nasm fails on the `prefix=_` argument. This is due to the version of nasm on conda being 2.13. The nasm on my debian 10 system (2.14) does not have this problem.

This PR updates nasm to ~~the latest stable version~~ 2.14 (2.15 gives windows build issues).

### CODE REVIEW

**Comment by rhpvorderman** [comment]
@jakirkham If you give your permission, I will add myself as maintainer to this package, as I am maintaining one of the packages that depends on nasm for building.

**Comment by rhpvorderman** [comment]
2.15.5 Does not build on windows. But 2.14 does. And 2.14 is all I need for building isa-l on mac.

**Comment by jakirkham** [comment]
> @jakirkham If you give your permission, I will add myself as maintainer to this package, as I am maintaining one of the packages that depends on nasm for building.

Thanks for the offer 😄 Yeah that would be great!

> 2.15.5 Does not build on windows. But 2.14 does. And 2.14 is all I need for building isa-l on mac.

No worries. Going to 2.14 sounds fine to me. Thanks for doing this 🙂

**Comment by rhpvorderman** [comment]
@jakirkham I am now in the maintainer list. This can be merged when ready :slightly_smiling_face: .

**Review by jakirkham — APPROVED** [review]

**Pull request merged**
